### ISSUE TITLE
Conflicts: 	LMPSystem/LMPSystem.suo

### ISSUE THREAD

**Issue by Bladefidz** [pradesga/labmedio#3]
Git not ignore the .suo file because the .suo file have been added to the master repository. Further information please read this:
http://stackoverflow.com/questions/11628418/git-cant-ignore-suo-file

Actually, other people not need to include .suo and .user file to adapt the other visual studio file. Further information please read this:
http://stackoverflow.com/questions/72298/should-i-add-the-visual-studio-suo-and-user-files-to-source-control

Please delete .suo file from repository.

**Comment by pradesga** [comment]
Go to offline discussions
